fix mkdocs --

diff --git a/.github/workflows/python-reusable.yml b/.github/workflows/python-reusable.yml
--- a/.github/workflows/python-reusable.yml
+++ b/.github/workflows/python-reusable.yml
@@ -282,16 +282,16 @@ jobs:
                   mkdocstrings-python==1.7.5
 
 
-        # Build documentation
-        cd ${{ inputs.project_path }}
-        mkdocs build -d ../site/${{ inputs.project_path }}
-        # Check if the build was successful
-        if [ $? -ne 0 ]; then
-          echo "Error: mkdocs build failed."
-          exit 1
-        fi
-        # Root documentation
-        mkdocs build -f mkdocs.yml -d site
+#        # Build documentation
+#        cd ${{ inputs.project_path }}
+#        mkdocs build -d ../site/${{ inputs.project_path }}
+#        # Check if the build was successful
+#        if [ $? -ne 0 ]; then
+#          echo "Error: mkdocs build failed."
+#          exit 1
+#        fi
+#        # Root documentation
+#        mkdocs build -f mkdocs.yml -d site
 #
 #        # Learning Python documentation
 #        cd learningpython
